---
- name: restart chrony
  service:
    name: chrony
    state: restarted
    enabled: true
  tags:
    - ntp
    - chrony

- name: chrony reload sources
  command:
    cmd: chronyc reload sources
  tags:
    - chrony

...
